"""History

Revision ID: 69d712fb5630
Revises: aba73f93fca3
Create Date: 2023-02-15 18:57:31.528005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d712fb5630'
down_revision = 'aba73f93fca3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
