"""Storage

Revision ID: 8e9fabf9ccff
Revises: 69d712fb5630
Create Date: 2023-02-15 18:59:17.460663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9fabf9ccff'
down_revision = '69d712fb5630'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
