"""AccountBalance

Revision ID: fb3a201eaad2
Revises: 8e9fabf9ccff
Create Date: 2023-02-15 18:59:53.794074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3a201eaad2'
down_revision = '8e9fabf9ccff'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
